name: DrMap
version: ${project.version}
main: org.acornmc.drmap.DrMap
api-version: 1.17
authors: [DrBot]
commands:
  drmap:
    description: create or reload
    permission: drmap.command
    usage: "/<command> create <url> [-s]\n/<command> reload\n/<command> erase\n/<command> author"
permissions:
  drmap.create:
    default: op
    description: create drmaps
    children:
      drmap.command: true
  drmap.reload:
    default: op
    description: reload plugin
    children:
      drmap.command: true
  drmap.erase:
    default: op
    description: erase drmaps
    children:
      drmap.command: true
  drmap.author:
    default: op
    description: info on who created drmaps
    children:
      drmap.command: true
  drmap.place:
    default: op
    description: place drmaps in item frames
  drmap.rotate:
    default: op
    description: rotate drmaps